import UIKit

/*
 You are given two strings s and t.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Return the letter that was added to t.

 Example 1:
 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 
 Example 2:
 Input: s = "", t = "y"
 Output: "y"
 
 Example 3:
 Input: s = "a", t = "aa"
 Output: "a"
 
 Example 4:
 Input: s = "ae", t = "aea"
 Output: "a"
  
 Constraints:
 0 <= s.length <= 1000
 t.length == s.length + 1
 s and t consist of lower-case English letters.
 */

func findTheDifference(_ s: String, _ t: String) -> Character {
    var res = s.unicodeScalars.reduce(0) { $0 ^ $1.value }
    res = t.unicodeScalars.reduce(res) { $0 ^ $1.value }
    return Character(UnicodeScalar(res)!)
}
